### ISSUE TITLE
Path to ghc libraries haddock

### ISSUE THREAD

**Issue by freizl** [sdiehl/wiwinwlh#60]
I'm seeing  ``file:///usr/share/doc/ghc-doc/html/libraries/index.html`` 
rather than ``file:///usr/share/doc/ghc/html/libraries/index.html``

platform: ubuntu-14
ghc: 7.6.3

**Comment by gliptak** [comment]
https://github.com/sdiehl/wiwinwlh/pull/93

**Comment by sdiehl** [comment]
Fixed in #93
